apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: docker.io/suahcho/mysql_db:2.0
        name: mysql-container
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: project-secret
              key: password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: project-secret
              key: database
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
          subPath: mysql
      imagePullSecrets:
      - name: regcred 
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: nfs-persistentvolumeclaim
---

apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port : 3306
  selector:
    app: mysql